import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/nav";
import Footer from "@/components/footer/footer";
import { AuthProvider } from "./KindeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Simple Next app",
  description: "Generated by Sakhawat Hossen",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en" data-theme="light" className="px-4 py-2">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <main className="container mx-auto min-h-screen">{children}</main>
        <Footer/>
      </body>
    </html>
    </AuthProvider>
  );
}
